import 'bloc/video_detail_unlock_error_one_bloc.dart';import 'models/video_detail_unlock_error_one_model.dart';import 'package:flutter/material.dart';import 'package:onito_s_application1/core/app_export.dart';import 'package:onito_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:onito_s_application1/widgets/app_bar/appbar_title_image.dart';import 'package:onito_s_application1/widgets/app_bar/appbar_trailing_image.dart';import 'package:onito_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:onito_s_application1/widgets/custom_elevated_button.dart';import 'package:onito_s_application1/widgets/custom_text_form_field.dart';class VideoDetailUnlockErrorOneScreen extends StatelessWidget {const VideoDetailUnlockErrorOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<VideoDetailUnlockErrorOneBloc>(create: (context) => VideoDetailUnlockErrorOneBloc(VideoDetailUnlockErrorOneState(videoDetailUnlockErrorOneModelObj: VideoDetailUnlockErrorOneModel()))..add(VideoDetailUnlockErrorOneInitialEvent()), child: VideoDetailUnlockErrorOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 22.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRectangle375, height: 258.v, width: 430.h), SizedBox(height: 21.v), Container(width: 323.h, margin: EdgeInsets.only(left: 20.h, right: 87.h), child: Text("msg_clinical_video_root".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge)), SizedBox(height: 19.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Row(children: [Container(width: 45.h, padding: EdgeInsets.symmetric(vertical: 4.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [CustomImageView(imagePath: ImageConstant.imgUnionOrange40012x6, height: 12.v, width: 6.h, margin: EdgeInsets.only(top: 1.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_5".tr, style: theme.textTheme.labelLarge))])), CustomElevatedButton(width: 100.h, text: "lbl_orthodontics".tr, margin: EdgeInsets.only(left: 16.h), leftIcon: Container(margin: EdgeInsets.only(right: 5.h), decoration: BoxDecoration(borderRadius: BorderRadius.circular(2.h)), child: CustomImageView(imagePath: ImageConstant.imgGoogle, height: 10.adaptSize, width: 10.adaptSize)))])), SizedBox(height: 26.v), CustomElevatedButton(height: 60.v, text: "lbl_m_kh_a2".tr.toUpperCase(), margin: EdgeInsets.symmetric(horizontal: 20.h), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: theme.textTheme.titleSmall!, alignment: Alignment.center), Spacer(), SizedBox(height: 36.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: BlocSelector<VideoDetailUnlockErrorOneBloc, VideoDetailUnlockErrorOneState, TextEditingController?>(selector: (state) => state.closeController, builder: (context, closeController) {return CustomTextFormField(controller: closeController, hintText: "msg_c_l_i_x_y_ra_h_y".tr, hintStyle: CustomTextStyles.bodyLarge16_3, textInputAction: TextInputAction.done, alignment: Alignment.center, prefix: Container(margin: EdgeInsets.fromLTRB(17.h, 30.v, 14.h, 30.v), child: CustomImageView(imagePath: ImageConstant.imgCloseOrange400, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 80.v), contentPadding: EdgeInsets.only(top: 30.v, right: 30.h, bottom: 30.v), borderDecoration: TextFormFieldStyleHelper.outlineBlack);}))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 36.h, top: 21.v, bottom: 19.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitleImage(imagePath: ImageConstant.imgGroup), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgSearchPrimary17x17, margin: EdgeInsets.fromLTRB(36.h, 20.v, 36.h, 18.v))]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
