import 'bloc/video_detail_unlock_error_bloc.dart';import 'models/video_detail_unlock_error_model.dart';import 'package:flutter/material.dart';import 'package:onito_s_application1/core/app_export.dart';import 'package:onito_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:onito_s_application1/widgets/app_bar/appbar_title_image.dart';import 'package:onito_s_application1/widgets/app_bar/appbar_trailing_image.dart';import 'package:onito_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:onito_s_application1/widgets/custom_elevated_button.dart';class VideoDetailUnlockErrorScreen extends StatelessWidget {const VideoDetailUnlockErrorScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<VideoDetailUnlockErrorBloc>(create: (context) => VideoDetailUnlockErrorBloc(VideoDetailUnlockErrorState(videoDetailUnlockErrorModelObj: VideoDetailUnlockErrorModel()))..add(VideoDetailUnlockErrorInitialEvent()), child: VideoDetailUnlockErrorScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<VideoDetailUnlockErrorBloc, VideoDetailUnlockErrorState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 22.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRectangle375, height: 258.v, width: 430.h), SizedBox(height: 21.v), Container(width: 323.h, margin: EdgeInsets.only(left: 20.h, right: 87.h), child: Text("msg_clinical_video_root".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge)), SizedBox(height: 19.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Row(children: [Container(width: 45.h, padding: EdgeInsets.symmetric(vertical: 4.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [CustomImageView(imagePath: ImageConstant.imgUnionOrange40012x6, height: 12.v, width: 6.h, margin: EdgeInsets.only(top: 1.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_5".tr, style: theme.textTheme.labelLarge))])), CustomElevatedButton(width: 100.h, text: "lbl_orthodontics".tr, margin: EdgeInsets.only(left: 16.h), leftIcon: Container(margin: EdgeInsets.only(right: 5.h), decoration: BoxDecoration(borderRadius: BorderRadius.circular(2.h)), child: CustomImageView(imagePath: ImageConstant.imgGoogle, height: 10.adaptSize, width: 10.adaptSize)))])), SizedBox(height: 26.v), CustomElevatedButton(height: 60.v, text: "lbl_m_kh_a2".tr.toUpperCase(), margin: EdgeInsets.symmetric(horizontal: 20.h), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: theme.textTheme.titleSmall!, alignment: Alignment.center), Spacer(), SizedBox(height: 36.v), _buildFortyNine(context)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 36.h, top: 21.v, bottom: 19.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitleImage(imagePath: ImageConstant.imgGroup), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgSearchPrimary17x17, margin: EdgeInsets.fromLTRB(36.h, 20.v, 36.h, 18.v))]); } 
/// Section Widget
Widget _buildFortyNine(BuildContext context) { return Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.symmetric(horizontal: 20.h), padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 22.v), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgUnionOrange40034x16, height: 34.v, width: 16.h, margin: EdgeInsets.only(top: 1.v)), Padding(padding: EdgeInsets.only(left: 16.h, top: 9.v, bottom: 7.v), child: Text("lbl_kh_ng_key".tr, style: CustomTextStyles.bodyLarge16_3)), Spacer(), CustomElevatedButton(height: 35.v, width: 75.h, text: "lbl_mua".tr, margin: EdgeInsets.only(top: 1.v, right: 1.h), buttonStyle: CustomButtonStyles.fillPrimaryTL17, buttonTextStyle: theme.textTheme.titleSmall!)]))); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
