import 'bloc/video_detail_unlock_success_bloc.dart';import 'models/video_detail_unlock_success_model.dart';import 'package:flutter/material.dart';import 'package:onito_s_application1/core/app_export.dart';import 'package:onito_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:onito_s_application1/widgets/app_bar/appbar_title_image.dart';import 'package:onito_s_application1/widgets/app_bar/appbar_trailing_image.dart';import 'package:onito_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:onito_s_application1/widgets/custom_elevated_button.dart';import 'package:onito_s_application1/widgets/custom_icon_button.dart';import 'package:onito_s_application1/widgets/custom_text_form_field.dart';class VideoDetailUnlockSuccessScreen extends StatelessWidget {const VideoDetailUnlockSuccessScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<VideoDetailUnlockSuccessBloc>(create: (context) => VideoDetailUnlockSuccessBloc(VideoDetailUnlockSuccessState(videoDetailUnlockSuccessModelObj: VideoDetailUnlockSuccessModel()))..add(VideoDetailUnlockSuccessInitialEvent()), child: VideoDetailUnlockSuccessScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 22.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildTimeStack(context), SizedBox(height: 15.v), Container(width: 323.h, margin: EdgeInsets.only(left: 20.h, right: 87.h), child: Text("msg_clinical_video_root".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge)), SizedBox(height: 19.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Row(children: [CustomElevatedButton(width: 40.h, text: "lbl_pro".tr, buttonTextStyle: CustomTextStyles.bodySmallOrange400), CustomElevatedButton(width: 100.h, text: "lbl_orthodontics".tr, margin: EdgeInsets.only(left: 11.h), leftIcon: Container(margin: EdgeInsets.only(right: 5.h), decoration: BoxDecoration(borderRadius: BorderRadius.circular(2.h)), child: CustomImageView(imagePath: ImageConstant.imgGoogle, height: 10.adaptSize, width: 10.adaptSize)))])), Spacer(), SizedBox(height: 36.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: BlocSelector<VideoDetailUnlockSuccessBloc, VideoDetailUnlockSuccessState, TextEditingController?>(selector: (state) => state.locationController, builder: (context, locationController) {return CustomTextFormField(controller: locationController, hintText: "msg_m_kh_a_th_nh_c_ng".tr, hintStyle: CustomTextStyles.bodyLarge16_3, textInputAction: TextInputAction.done, alignment: Alignment.center, prefix: Container(margin: EdgeInsets.fromLTRB(19.h, 30.v, 14.h, 30.v), child: CustomImageView(imagePath: ImageConstant.imgLocationOrange400, height: 13.v, width: 17.h)), prefixConstraints: BoxConstraints(maxHeight: 80.v), contentPadding: EdgeInsets.only(top: 30.v, right: 30.h, bottom: 30.v), borderDecoration: TextFormFieldStyleHelper.outlineBlack);}))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 36.h, top: 21.v, bottom: 19.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitleImage(imagePath: ImageConstant.imgGroup), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgSearchPrimary17x17, margin: EdgeInsets.fromLTRB(36.h, 20.v, 36.h, 18.v))]); } 
/// Section Widget
Widget _buildTimeStack(BuildContext context) { return SizedBox(height: 264.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.center, child: SizedBox(height: 258.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle375, height: 258.v, width: 430.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: SizedBox(height: 258.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Container(width: double.maxFinite, margin: EdgeInsets.only(bottom: 1.v), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 18.v), decoration: AppDecoration.fillBlack9001, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 5.h, top: 203.v), child: Text("lbl_08_05".tr, style: CustomTextStyles.bodyMedium_2)), Spacer(flex: 64), Padding(padding: EdgeInsets.only(top: 85.v, bottom: 84.v), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(14.h), child: CustomImageView(imagePath: ImageConstant.imgPlay))), Spacer(flex: 35), Padding(padding: EdgeInsets.only(top: 203.v), child: Text("lbl_19_45".tr, style: CustomTextStyles.bodyMedium_2)), CustomImageView(imagePath: ImageConstant.imgProfilePrimary, height: 15.adaptSize, width: 15.adaptSize, margin: EdgeInsets.only(left: 15.h, top: 205.v)), CustomImageView(imagePath: ImageConstant.imgVector, height: 15.v, width: 20.h, margin: EdgeInsets.only(left: 16.h, top: 203.v))]))), Align(alignment: Alignment.bottomCenter, child: SizedBox(height: 3.v, width: double.maxFinite, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: SizedBox(width: double.maxFinite, child: Divider())), Align(alignment: Alignment.centerLeft, child: SizedBox(width: 172.h, child: Divider(color: theme.colorScheme.primary)))])))])))]))), Align(alignment: Alignment.bottomLeft, child: Container(height: 15.adaptSize, width: 15.adaptSize, margin: EdgeInsets.only(left: 167.h), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(7.h), boxShadow: [BoxShadow(color: appTheme.black900.withOpacity(0.25), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 1))])))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
