import 'bloc/login_one_bloc.dart';import 'models/login_one_model.dart';import 'package:flutter/material.dart';import 'package:onito_s_application1/core/app_export.dart';import 'package:onito_s_application1/core/utils/validation_functions.dart';import 'package:onito_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:onito_s_application1/widgets/app_bar/appbar_title_image.dart';import 'package:onito_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:onito_s_application1/widgets/custom_elevated_button.dart';import 'package:onito_s_application1/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class LoginOneScreen extends StatelessWidget {LoginOneScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<LoginOneBloc>(create: (context) => LoginOneBloc(LoginOneState(loginOneModelObj: LoginOneModel()))..add(LoginOneInitialEvent()), child: LoginOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 35.h, vertical: 21.v), child: Column(children: [BlocSelector<LoginOneBloc, LoginOneState, TextEditingController?>(selector: (state) => state.mobileNoController, builder: (context, mobileNoController) {return CustomTextFormField(controller: mobileNoController, hintText: "lbl_0988089996".tr, textInputType: TextInputType.phone, validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;}, borderDecoration: TextFormFieldStyleHelper.fillOnPrimary);}), SizedBox(height: 15.v), BlocBuilder<LoginOneBloc, LoginOneState>(builder: (context, state) {return CustomTextFormField(controller: state.settingsController, hintText: "lbl_m_t_kh_u".tr, hintStyle: CustomTextStyles.bodyLargeOnPrimaryContainer16, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, suffix: InkWell(onTap: () {context.read<LoginOneBloc>().add(ChangePasswordVisibilityEvent(value: !state.isShowPassword));}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 23.v, 22.h, 23.v), child: CustomImageView(imagePath: ImageConstant.imgSettings, height: 13.v, width: 20.h))), suffixConstraints: BoxConstraints(maxHeight: 60.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: state.isShowPassword, contentPadding: EdgeInsets.only(left: 22.h, top: 20.v, bottom: 20.v));}), SizedBox(height: 20.v), Align(alignment: Alignment.centerRight, child: Opacity(opacity: 0.5, child: Padding(padding: EdgeInsets.only(right: 22.h), child: Text("lbl_qu_n_m_t_kh_u".tr, style: CustomTextStyles.bodyMediumOnPrimaryContainer_1)))), Spacer(flex: 35), RichText(text: TextSpan(children: [TextSpan(text: "msg_ch_a_c_t_i_kho_n2".tr, style: CustomTextStyles.bodyMediumPrimary), TextSpan(text: " "), TextSpan(text: "lbl_ng_k".tr, style: CustomTextStyles.titleSmallPrimary)]), textAlign: TextAlign.left), SizedBox(height: 43.v), CustomElevatedButton(height: 60.v, text: "lbl_ng_nh_p".tr.toUpperCase(), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: theme.textTheme.titleSmall!), Spacer(flex: 64)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftPrimary, margin: EdgeInsets.only(left: 36.h, top: 19.v, bottom: 21.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitleImage(imagePath: ImageConstant.imgGroup)); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
